learn_website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('webApp.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webApp/urls.py
from django.urls import path,include
from.import views

urlpatterns = [

    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('courses', views.courses, name='courses'),
    path('placement',views.placement,name="placement"),
    path('subscribe',views.subscribe,name="subscribe"),
    path('contactuss',views.contactuss,name="contactuss"),
    path('saveEnquiry',views.saveEnquiry,name="saveEnquiry"),

    path('python_dev',views.python_dev,name="python_dev"),
    path('react_dev',views.react_dev,name="react_dev"),
    path('rest_api',views.rest_api,name="rest_api"),
    path('digital_marketing',views.digital_marketing,name="digital_marketing"),
    
    path('frontend_dev',views.frontend_dev,name="frontend_dev"),
    path('course_select/<pk>',views.course_select,name = "course_select"),

    path('ojt',views.ojt,name="ojt"),
    path('internships',views.internships,name="internships"),
    path('short_term',views.short_term,name="short_term"),
]

webApp/models.py
from django.db import models

class Subscriber(models.Model):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email
    
class about_model(models.Model):
    video_file = models.FileField(upload_to='videos/',null= True)
    description = models.CharField(max_length=255,null=True,blank=True)

class course_details(models.Model):
    image = models.ImageField(null=True,blank = True,upload_to = 'img/courses')
    course_name = models.CharField(max_length=255, null=True,blank=True)
    description = models.CharField(max_length=255,null=True,blank=True)
    fee = models.IntegerField(null=True,blank=True)
    duration = models.CharField(max_length=100,null=True,blank=True)
    start_date = models.DateField(null=True,blank=True)
    # course_url = models.URLField(max_length=200,null=True,blank=True)

class course_description_list(models.Model):
    list_item = models.CharField(max_length=100)
    course = models.ManyToManyField('course_details')

class instructors(models.Model):
    image = models.ImageField(null=True,blank = True,upload_to = 'img/instructors')
    name = models.CharField(max_length=255, null=True,blank=True)
    designation = models.CharField(max_length=255,null=True,blank=True)
    description = models.CharField(max_length=255,null=True,blank=True)

class testimonial(models.Model):
    image = models.ImageField(null=True,blank = True,upload_to = 'img/testimonial')
    name = models.CharField(max_length=255, null=True,blank=True)
    profession = models.CharField(max_length=255,null=True,blank=True)
    company = models.CharField(max_length=100,null=True,blank=True)
    description = models.CharField(max_length=255,null=True,blank=True)

class contactus(models.Model):

    name = models.CharField(max_length=255, null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    subject = models.CharField(max_length=255,null=True,blank=True)
    message = models.CharField(max_length=100,null=True,blank=True)

class gallery(models.Model):
    image = models.ImageField(null=True,blank = True,upload_to = 'img/gallery')

class enquiry(models.Model):
    name = models.CharField(max_length=255, null=True,blank=True)
    email = models.CharField(max_length=255,null=True,blank=True)
    phone = models.CharField(max_length=100,null=True,blank=True)
    course = models.CharField(max_length=100,null=True,blank=True)
    message = models.CharField(max_length=255,null=True,blank=True)

webApp/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.utils.text import capfirst
from .models import *
import random



def index(request):
    video = about_model.objects.all()
    courses = course_details.objects.all()
    mentors = instructors.objects.all()
    reviews = testimonial.objects.all()
    context = {
        'video' : video,
        'courses' :courses,
        'mentors' : mentors,
        'review' :reviews
    }
    return render(request,'index.html',context)

def about(request):
    video = about_model.objects.all()
    mentors = instructors.objects.all()

    context = {
        'video' : video,
        'mentors' : mentors,
    }
    return render(request,'about.html', context)

def courses(request):
    courses = course_details.objects.all()
    context = {
        'courses' : courses,
    }
    return render(request,'courses.html',context)

def contact(request):
    return render(request,'contact.html')


def placement(request):
    return render(request,'placement.html')


def subscribe(request):
    if request.method == 'POST':
        email = request.POST['email']
        Subscriber(email = email).save()
    return redirect('/')
def contactuss(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['msg']
    
        contactus(name = name, email = email, subject = subject, message = message).save()

    return redirect('/contact')


def python_dev(request):
    return render(request,'python.html')

def react_dev(request):
    return render(request,'react.html')

def rest_api(request):
    return render(request,'restapi.html')

def digital_marketing(request):
    return render(request,'digital.html')

def frontend_dev(request):
    return render(request,'frontend.html')

def course_select(request,pk):

    # print(pk)
    if pk == 1:
        return redirect('python_dev')
    elif pk == 2:
        return render(request,'react.html')
    elif pk == 3:
        return render(request,'frontend.html')
    elif pk == 4:
        return render(request,'restapi.html')
    else:
        return render(request,'digital.html')


def saveEnquiry(request):

    if request.method == 'POST':
        
        name = request.POST.get('join_name')
        email = request.POST.get('join_email')
        phn = request.POST.get('join_phone')
        course = request.POST.get('course')
        message = request.POST.get('join_message')
        print(name)
        enquiry(name = name, email = email, phone = phn, course = course, message = message).save()

    return redirect('index')


def ojt(request):
    return render(request,'ojt.html')

def internships(request):
    return render(request,'internship.html')

def short_term(request):
    return render(request,'short_term.html')

webApp/templates/contact.html
{% extends 'base.html'%}
{% block content %}
{% load static %}

<link href="static/img/favicon.ico" rel="icon">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

<style>
    h1{
        color: var(--light);
    }
    .contact-section p{
        text-align: justify; 
        text-justify: distribute; 
        font-size: 18px; 
        color: var(--light);
        line-height: 1rem;
    }
    iframe{
        height: 350px; 
        width: 350px; 
        border:0;
    }
    @media screen and (min-width:900px) and (max-width: 1390px) {
        iframe{
        height: 350px; 
        width: 350px; 
        border:0;
    }
}
 @media screen and (min-width:400px) and (max-width: 900px) {
    iframe{
        height: 350px; 
        width: 350px; 
        border:0;
    }

 }
    @media screen and (min-width:280px) and (max-width: 450px) {
        iframe{
        height: 350px; 
        width: 300px; 
        border:0;
    }
    }

</style>
    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page-header">
        <div class="container py-0 ">
            <nav class ="breadcrumb" aria-label="breadcrumb justify-content-right" >
                <ol class="breadcrumb ">
                    <li class="breadcrumb-item"><a class="text-white" href="{% url 'index'  %}">Home</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Contact Us</li>
                </ol>
            </nav>
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h6 class="section-title bg-white text-center text-primary px-3">Contact Us</h6>
                    <h1 class="mb-5">Contact For Any Query</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- Contact Start -->
    <div class="container-xxl py-5">
        <div class="container contact-section">
            <!-- <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Contact Us</h6>
                <h1 class="mb-5">Contact For Any Query</h1>
            </div> -->
            <div class="col-lg-12 wow fadeInUp justify-content-center p-1 m-1" data-wow-delay="0.3s">
                
                <p class=" text-light mt-1 p-1" >
                    Welcome to Altos Eduhub's Contact Us page! We're thrilled that you're interested in our
on-the-job training programs and would love to hear from you.
 
                <p class="mb-5 p-1">
                    Whether you have questions about our training programs or are ready to enroll, our team of
experts is here to help you every step of the way.

                </p>                
            </div>

            <div class="row g-4">
                <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                    <h4>Get In Touch</h4>
                    <p class="mb-4" style="text-align: justify; text-justify: distribute; font-size: 16px; font-family: 'Nunito',sans-serif;">To get in touch with us, simply fill out the contact form on this page or email us at info@Altostechnologies.in . Our team will get back to you as soon as possible to address your inquiry.</a></p>
                    <div class="d-flex align-items-center mb-3">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
                            <i class="fa fa-map-marker-alt text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Office</h5>
                            <p class="mb-0">1st Floor - Thapasya Building Infopark,
                                Kakkanad, Cochin</p>
                        </div>
                    </div>
                    <div class="d-flex align-items-center mb-3">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
                            <i class="fa fa-phone-alt text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Mobile</h5>
                            <p class="mb-0">+91 974 663 2202</p>
                        </div>
                    </div>
                    <div class="d-flex align-items-center">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary" style="width: 50px; height: 50px;">
                            <i class="fa fa-envelope-open text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Email</h5>
                            <p class="mb-0">info@Altostechnologies.in</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
                    <!-- <iframe class="position-relative rounded w-100 h-100"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                        frameborder="0" style="min-height: 300px; border:0;" allowfullscreen="" aria-hidden="false"
                        tabindex="0"></iframe> -->
                        <iframe src="https://www.google.com/maps/embed?pb=!1m19!1m8!1m3!1d2012604.068571148!2d76.524882!3d9.861497!3m2!1i1024!2i768!4f13.1!4m8!3e0!4m0!4m5!1s0x3b080d9bfaa6db61%3A0xa5df6acfc2d1e5fd!2sALTOS%20Technologies%2C%201st%20floor%2C%20Thapasaya%20Building%2C%20Infopark%2C%20Kakanad%2C%20Kochi%2C%20Kerala%20682042!3m2!1d10.0107422!2d76.36069859999999!5e0!3m2!1sen!2sin!4v1682016534785!5m2!1sen!2sin" 
                         allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
                <div class="col-lg-4 col-md-12 wow fadeInUp" data-wow-delay="0.5s">
                    <form action="{% url 'contactuss' %}" method='post' enctype="multipart/form-data">

                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="name" name="name" placeholder="Your Name">
                                    <label for="name">Name</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="email" class="form-control" id="email" name="email" placeholder="Your Email">
                                    <label for="email">Email</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="subject" name="subject" placeholder="Subject">
                                    <label for="subject">Subject</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
                                    <textarea class="form-control"
                                     placeholder="Leave a message here" id="message" name="msg" style="height: 150px"></textarea>
                                     <label for="message">Message</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button class="btn btn-primary w-100 py-3" type="submit" onclick="sendMessage()">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->

    <!-- messageBox -->
    <div id="messageBox">
        <p id="messageText"></p>
        <button class="text-center justify-content-center" id="closeButton" onclick="closeMessageBox()">Close</button>
      </div>

      <!-- end messageBox -->
      <style>

            #messageBox {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background-color: var(--primary);
            border-radius: 10px;
            padding: 20px;
            display: none;
            }

            #messageText {
            font-size: 20px;
            font-weight: bold;
            margin: 0 0 10px 0;
            color: var(--dark);
            }

            #closeButton {
            background-color: var(--dark);
            color: #fff;
            border: none;
            border-radius: 10px;
            padding: 10px;
            margin-top: 10px;
            cursor: pointer;
            margin-left: 100px;
            }
      </style>
    <script>
        function sendMessage() {

            var nameInput = document.getElementById("name").value;
            var emailInput = document.getElementById("email").value;
            var messageInput = document.getElementById("message").value;
            var messageBox = document.getElementById("messageBox");
            var messageText = document.getElementById("messageText");
            
            if (nameInput === "" || emailInput === "" || messageInput === "") {
                messageText.innerText = "Please fill in all fields before sending the message.";
                messageBox.style.display = "block";
            } else {
                messageText.innerText = "We will get back to you as soon as possible";
                messageBox.style.display = "block";
            }
            }

            function closeMessageBox() {
            var messageBox = document.getElementById("messageBox");
            messageBox.style.display = "none";
            }

    </script>

    {% endblock %}

webApp/templates/courses.html
{% extends 'base.html'%}
{% block content %}
{% load static %}

<link href="static/img/favicon.ico" rel="icon">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

<style>
    h1{
        color: var(--light);
    }
    p, li,small{
        font-size: 18px;
        text-align: justify;
        text-justify: distribute;
    }
    .course-item{

        height: 750px !important;
        overflow:scroll;
    }
    @media (min-width: 600px)and ( max-width:1000px) {

        .course-item{
            height: 625px !important;
            overflow:scroll;        
        }
    }
    @media (min-width: 300px)and ( max-width:800px) {

        .course-item{
            height: 650px !important;
            overflow:scroll;
    }
    }

    p{
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        text-align: justify; 
        text-justify: distribute; 
        font-size: 17px; 
        color: var(--light);
        line-height: 2rem;
    }

</style>

    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page-header">
        <div class="container py-0 ">
            <nav class ="breadcrumb" aria-label="breadcrumb justify-content-right" >
                <ol class="breadcrumb ">
                    <li class="breadcrumb-item"><a class="text-white" href="{% url 'index'  %}">Home</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Courses</li>
                </ol>
            </nav>
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center wow fadeInUp">
                    <h6 class="section-title bg-dark text-center text-primary px-3">Courses</h6>
                    <h1 class="mb-5">Learn with us</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


<!-- Courses Start -->
<div class="container-xxl py-5">
    <div class="container courses-section justify-content-between">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <!-- <h6 class="section-title bg-white text-justify text-primary px-3">Courses</h6>
            <h1 class="mb-5">On the Job Training</h1> -->
            <!-- <hr> -->
            <p class=" text-light mt-1 p-1">
                Welcome to Altos Eduhub - the premier software training company in Kerala, and a subsidiary of
                Altos Technologies - one of the leading software development companies in Kochi. We offer a
                range of on-the-job training programs in Python, React JS, Front End Development, REST API,
                and Digital Marketing. Our courses are designed to equip you with the skills and knowledge you
                need to succeed in the competitive world of software development.
                <p class="p-1">
                Our training programs are six months in duration, with the first three months focused on
                fundamental training and the remaining three months dedicated to practical work on live
                projects. Upon successful completion of the training, you will receive an experience certificate.
                For Python training, we also offer guaranteed placement at Altos Technologies, while for other
                programs, we provide placement assistance.</p>
                <p class="mb-5 p-1">
                To ensure the best possible training experience for our candidates, we have implemented
                several measures. As a part of our training program, we provide candidates with access to Altos
                core software, where they can update their tasks and track their work status efficiently.
                Additionally, we conduct weekly meetings for each of the candidates to evaluate their work and
                performance. We believe in providing continuous support to our candidates and offer a doubt
                clearing section that is available 24 hours a day, seven days a week.
            </p>
        </div>

        <style>
            .points ul {
                list-style-type: none;
            }
            .points ul li{
                font-size: 17px; 
                color: var(--light);
                line-height: 2rem;
                text-align: justify;
                text-justify: distribute-all-lines;
            }
            .points ul li::before {
                content: "-►";
                color: var(--primary);
                font-size: 20px;
                margin-right: 5px;
            }
        </style>
        <div class="text-center animated slideInRight points" data-wow-delay="0.1s">
            <h3 class="mb-5 animated slideInLeft">Why Altos Eduhub ?</h3>
            <hr>
            <div class="row gy-2 gx-4 mb-5 " >
                    
                <div class="col-sm-6 text-center m-0 p-0" style="margin-right: 0;">
                    <ul>
                        <li class="p-1" >Experience certificate upon successful completion of training</li>
                        <li class="p-1">Assured placement assistance for certain programs</li>
                        <li class="p-1">24-hour doubt clearing assistance for all candidates</li>
                        <li class="p-1" >Training on live projects to gain hands-on experience</li>
                        <li class="p-1" >Career development guidance to help candidates achieve their career goals</li>
                    </ul>
                </div>
                <div class="col-sm-6 text-center m-0 p-0" style="margin-left: 0;">
                    <ul>
                        <li class="p-1" >Highly experienced trainers with years of industry experience</li>
                        <li class="p-1" >Access to Altos core software for tracking training progress and work status</li>
                        <li class="p-1" >Weekly meetings to evaluate work and performance</li>
                        <li class="p-1" >Convenient EMI payment options for training program fees</li>
                        <li class="p-1" >Located in Infopark, Kochi - a premier technology park with state-of-the-art facilities</li>
                    </ul>
                </div>

            </div>
        </div>

        <div class="row g-4  justify-content-center" >
            <div class="text-center wow fadeInLeftBig">
                <h3 class="mb-5">Offered Courses</h3>
            </div>
            <hr>
            {% for c in courses %}
            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s" >
                <div class="course-item bg-light">
                   
                    <div class="position-relative overflow-hidden">

                        {% if c.image %}
                            <img src="{{ c.image.url }}" class="img-fluid" style="width:500px; height: 235px !important;">
                        {% endif %}

                        <div class="w-100 d-flex justify-content-center position-absolute bottom-0 start-0 mb-4">
                            <a href="#" class="flex-shrink-0 btn btn-sm btn-primary px-3 border-end" style="border-radius: 30px 0 0 30px;">Read More</a>
                            <a href="#" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 0 30px 30px 0;">Join Now</a>
                        </div>
                    </div>
                    <div class="text-center p-4 pb-0">
                      
                        <h4 class="mb-1 text-center ">{{c.course_name}}  </h4>
                        
                        <p class="mb-2 p-2 text-dark">{{c.description}}Some of the tools and technologies that can be
                            offered as part of the program are:
                            </p>
                        <ol>
                            {% for s in c.course_description_list_set.all %}
                                <li>{{ s.list_item }}</li>
                            {% endfor %}
                        </ol>
                        <h5 class="mb-1 text-left"><b>Course Fee:</b>{%if c.fee is not None %} ₹{{c.fee}}.00 {% endif %}</h5>
                    </div>
                    <div class="d-flex border-top">
                        <small class="flex-fill text-center border-end py-3"><b>Next Batch </b> <br>{%if c.start_date is not None %} {{c.start_date}} {% endif %}</small>
                        <small class="flex-fill text-center border-end py-3"><b>Duration  </b> <br>{%if c.duration is not None %} {{c.duration}} {% endif %}</small>
                    </div>
                    
                </div>
            </div>
            {% endfor %}
           

        </div>
    </div>
</div>
<!-- Courses End -->



        
    {% endblock %}

webApp/templates/digital.html
{% extends 'base.html'%}
{% block content %}
{% load static %}

<link href="static/img/favicon.ico" rel="icon">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

<style>
    h1{
        color: var(--light);
    }
</style>

    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page-header">
        <div class="container py-0 ">
            <nav class ="breadcrumb" aria-label="breadcrumb justify-content-right" >
                <ol class="breadcrumb ">
                    <li class="breadcrumb-item"><a class="text-white" href="{% url 'index'  %}">Home</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Digital Marketing</li>
                </ol>
            </nav>
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h6 class="section-title bg-white text-center text-primary px-3">Digital Marketing</h6>
                    <h1 class="mb-5">Know more about this Course</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

{% endblock %}

webApp/templates/frontend.html
{% extends 'base.html'%}
{% block content %}
{% load static %}

<link href="static/img/favicon.ico" rel="icon">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
<style>
    h1{
        color: var(--light);
    }
</style>


    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page-header">
        <div class="container py-0 ">
            <nav class ="breadcrumb" aria-label="breadcrumb justify-content-right" >
                <ol class="breadcrumb ">
                    <li class="breadcrumb-item"><a class="text-white" href="{% url 'index'  %}">Home</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Frontend</li>
                </ol>
            </nav>
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h6 class="section-title bg-white text-center text-primary px-3">Frontend Development</h6>
                    <h1 class="mb-5">Know more about this Course</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

{% endblock %}

webApp/templates/python.html
{% extends 'base.html'%}
{% block content %}
{% load static %}

<link href="static/img/favicon.ico" rel="icon">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

<style>
    h1{
        color: var(--light);
    }
</style>
    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page-header">
        <div class="container py-0 ">
            <nav class ="breadcrumb" aria-label="breadcrumb justify-content-right" >
                <ol class="breadcrumb ">
                    <li class="breadcrumb-item"><a class="text-white" href="{% url 'index'  %}">Home</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Python</li>
                </ol>
            </nav>
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h6 class="section-title bg-white text-center text-primary px-3">Python Development</h6>
                    <h1 class="mb-5">Know more about this Course
                        
                    </h1>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


{% endblock %}